# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - storage/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vars1

steps:
- script: echo $(BC_API_KEY)
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install bridgecrew
  displayName: 'Install the Bridgecrew CLI'
- script: bridgecrew -d storage
  displayName: 'Scan with Bridgecrew'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'arm-service-connection'
    subscriptionId: '6e1d96d8-e736-4089-a694-908b1f5ceea2'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg1'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'storage/storage.json'
    deploymentMode: 'Incremental'