# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  paths:
    include:
      - storage/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: vars1

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install bridgecrew
  displayName: 'Install the Bridgecrew CLI'
- script: bridgecrew -d storage --bc-api-key $BC_API_KEY --repo-id mikeubanski1/azure-arm --branch master
  displayName: 'Scan with Bridgecrew'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'arm-service-connection'
    subscriptionId: '69a2258c-8778-4d42-9ea7-6b65af91ffc3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'bcazr3'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'storage/storage.json'
    deploymentMode: 'Incremental'
